##############################################################################
#
# NixOS Production Workstation
#
# Hostname : ghost
# Purpose  : Daily Development Workstation
# Desktop  : GNOME Wayland
# Shell    : Bash
# Boot     : systemd-boot
# Storage  : LUKS + ext4
#
# Philosophy
#
#  • Single configuration.nix
#  • No flakes
#  • No Home Manager
#  • Git-managed dotfiles
#  • Production-ready
#  • Readable
#  • Well documented
#
##############################################################################

{ config, pkgs, lib, ... }:

let

  ###########################################################################
  #
  # User Settings
  #
  ###########################################################################

  username = "stefan-hacks";

  fullName = "stefan-hacks";

  homeDirectory = "/home/${username}";

  ###########################################################################
  #
  # Dotfiles
  #
  ###########################################################################

  dotfilesDirectory = "$HOME/.config/nixit/dotfiles";

in

{

##############################################################################
#
# Imports
#
# Keep hardware-configuration.nix separate.
#
# This file contains machine-specific information generated by the installer,
# including filesystems, swap devices, kernel modules and hardware detection.
#
##############################################################################

imports = [

  ./hardware-configuration.nix

];

##############################################################################
#
# Boot Loader
#
# IMPORTANT
#
# This section mirrors the working configuration generated during
# installation.
#
# Do NOT replace UUIDs or encryption devices unless reinstalling.
#
##############################################################################

boot = {

  loader = {

    systemd-boot.enable = true;

    efi.canTouchEfiVariables = true;

  };

  initrd = {

    luks.devices = {

      "luks-a647bf68-5914-4ce0-b703-59f782388611" = {

        device =
          "/dev/disk/by-uuid/a647bf68-5914-4ce0-b703-59f782388611";

      };

    };

  };

};

##############################################################################
#
# Nix
#
##############################################################################

nix = {

  settings = {

    experimental-features = [

      "nix-command"

    ];

    auto-optimise-store = true;

    warn-dirty = false;

    trusted-users = [

      "root"
      "@wheel"

    ];

  };

  gc = {

    automatic = true;

    dates = "weekly";

    options = "--delete-older-than 30d";

  };

};

##############################################################################
#
# Nixpkgs
#
##############################################################################

nixpkgs.config.allowUnfree = true;

##############################################################################
#
# System
#
##############################################################################

system.stateVersion = "26.05";

##############################################################################
#
# Networking
#
##############################################################################

networking = {

  hostName = "ghost";

  networkmanager.enable = true;

};

##############################################################################
#
# Time
#
##############################################################################

time.timeZone = "America/Sao_Paulo";

##############################################################################
#
# Localisation
#
##############################################################################

i18n = {

  defaultLocale = "en_US.UTF-8";

  extraLocaleSettings = {

    LC_ADDRESS        = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT    = "en_US.UTF-8";
    LC_MONETARY       = "en_US.UTF-8";
    LC_NAME           = "en_US.UTF-8";
    LC_NUMERIC        = "en_US.UTF-8";
    LC_PAPER          = "en_US.UTF-8";
    LC_TELEPHONE      = "en_US.UTF-8";
    LC_TIME           = "en_US.UTF-8";

  };

};

##############################################################################
#
# Console
#
##############################################################################

console = {

  keyMap = "us";

};

##############################################################################
#
# X11 / Wayland
#
##############################################################################

services.xserver = {

  enable = true;

  xkb = {

    layout = "us";

    variant = "";

  };

};

##############################################################################
#
# GNOME Desktop
#
##############################################################################

services.displayManager.gdm.enable = true;

services.desktopManager.gnome.enable = true;

##############################################################################
#
# DConf
#
##############################################################################

programs.dconf.enable = true;

##############################################################################
#
# XDG Portal
#
# Required for Wayland, Flatpak, screenshots, screen sharing and desktop
# integration.
#
##############################################################################

xdg.portal = {

  enable = true;

  xdgOpenUsePortal = true;

  extraPortals = with pkgs; [

    xdg-desktop-portal-gnome

  ];

};

##############################################################################
#
# Audio
#
##############################################################################

security.rtkit.enable = true;

services.pipewire = {

  enable = true;

  pulse.enable = true;

  alsa.enable = true;

  alsa.support32Bit = true;

  jack.enable = true;

};

##############################################################################
#
# Bluetooth
#
##############################################################################

hardware.bluetooth = {

  enable = true;

  powerOnBoot = true;

};

# services.blueman.enable = true;

##############################################################################
#
# Printing
#
##############################################################################

services.printing.enable = true;

##############################################################################
#
# Network Discovery
#
##############################################################################

services.avahi = {

  enable = true;

  nssmdns4 = true;

  openFirewall = true;

};

##############################################################################
#
# Flatpak
#
##############################################################################

# services.flatpak.enable = true;

##############################################################################
#
# Firmware Updates
#
##############################################################################

services.fwupd.enable = true;

##############################################################################
#
# Power Management
#
##############################################################################

powerManagement.enable = true;

services.power-profiles-daemon.enable = true;

##############################################################################
#
# User Account
#
##############################################################################

users.users.${username} = {

  isNormalUser = true;

  description = fullName;

  shell = pkgs.bash;

  extraGroups = [

    "wheel"
    "networkmanager"
    "audio"
    "video"
    "input"
    "dialout"

  ];

};

##############################################################################
#
# Bash
#
# Bash itself is enabled here.
#
# All personal shell configuration lives inside the dotfiles repository.
#
##############################################################################

programs.bash = {

  enable = true;

  completion.enable = true;

};

##############################################################################
#
# Git
#
# Git configuration is provided via ~/.gitconfig from the dotfiles repository.
#
##############################################################################

programs.git.enable = true;

##############################################################################
#
# OpenSSH
#
##############################################################################

programs.ssh = {

  startAgent = true;

};

##############################################################################
#
# GnuPG
#
##############################################################################

programs.gnupg.agent = {

  enable = true;

  enableSSHSupport = true;

};

##############################################################################
#
# Dotfile Deployment
#
# The activation script creates symbolic links from the Git repository into
# the user's home directory.
#
# The repository remains the single source of truth.
#
##############################################################################

system.activationScripts.dotfiles.text = ''

  DOTFILES="${$HOME/.config/nixit/dotfiles}"
  HOME="${homeDirectory}"

  mkdir -p "$HOME/.config"

  ln -sfn "$DOTFILES/bash/.bashrc"              "$HOME/.bashrc"
  ln -sfn "$DOTFILES/bash/.bash_aliases"              "$HOME/.bash_aliases"
  ln -sfn "$DOTFILES/gitconfig/.gitconfig"           "$HOME/.gitconfig"
  ln -sfn "$DOTFILES/kitty/kitty.conf"                "$HOME/.config/kitty/kitty.conf"
  ln -sfn "$DOTFILES/kitty/current_theme.conf"                "$HOME/.config/kitty/current_theme.conf"
  ln -sfn "$DOTFILES/kanata/kanata.kbd"                "$HOME/.config/kanata/kanata.kbd"
  # ln -sfn "$DOTFILES/nvim"                 "$HOME/.config/nvim"
  # ln -sfn "$DOTFILES/atuin"                "$HOME/.config/atuin"
  ln -sfn "$DOTFILES/starship/starship.toml"        "$HOME/.config/starship.toml"

  # Add additional dotfile links below as your repository grows.

'';

##############################################################################
#
# Environment Variables
#
##############################################################################

environment.variables = {

  EDITOR = "nvim";

  VISUAL = "nvim";

  TERMINAL = "kitty";

  BROWSER = "firefox";

};

##############################################################################
#
# Fonts
#
##############################################################################

fonts = {

  fontDir.enable = true;

  packages = with pkgs; [

    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji

    liberation_ttf
    dejavu_fonts

    nerd-fonts.jetbrains-mono

    inter

  ];

};

##############################################################################
#
# Environment Packages
#
# These packages are installed system-wide.
#
# User configuration remains inside the dotfiles repository.
#
##############################################################################

environment.systemPackages = with pkgs; [

  ###########################################################################
  # Core Utilities
  ###########################################################################

  bash
  coreutils
  findutils
  gnugrep
  gnused
  gawk
  util-linux
  file
  which
  tree
  wget
  curl
  rsync
  unzip
  zip
  p7zip

  ###########################################################################
  # Shell Utilities
  ###########################################################################

  blesh
  atuin
  starship
  zoxide
  fzf
  direnv

  eza
  bat
  ripgrep
  fd

  jq
  yq-go

  less

  ###########################################################################
  # Editors
  ###########################################################################

  neovim

  ###########################################################################
  # Git
  ###########################################################################

  git
  git-lfs
  delta
  gh

  ###########################################################################
  # Networking
  ###########################################################################

  inetutils

  dnsutils

  nmap

  mtr

  traceroute

  tcpdump

  wireshark

  openssh

  ###########################################################################
  # Archives
  ###########################################################################

  xz
  gzip
  bzip2

  ###########################################################################
  # Monitoring
  ###########################################################################

  btop

  fastfetch

  lsof

  pciutils

  usbutils

  lm_sensors

  smartmontools

  nvme-cli

  ###########################################################################
  # Nix
  ###########################################################################

  nix-tree

  nix-output-monitor

  nix-index

  comma

];

##############################################################################
#
# Development
#
##############################################################################

programs.direnv = {

  enable = true;

  nix-direnv.enable = true;

};

##############################################################################
#
# SSH Server
#
# Disabled by default.
#
##############################################################################

services.openssh = {

  enable = false;

};

##############################################################################
#
# Virtualisation
#
##############################################################################

virtualisation = {

  docker.enable = false;

  podman.enable = false;

  libvirtd.enable = false;

};

##############################################################################
#
# Firewall
#
##############################################################################

networking.firewall = {

  enable = true;

};

##############################################################################
#
# Automatic Maintenance
#
##############################################################################

services.fstrim.enable = true;

##############################################################################
#
# Command Not Found
#
##############################################################################

programs.command-not-found.enable = true;

##############################################################################
#
# Documentation
#
##############################################################################

documentation = {

  enable = true;

  man.enable = true;

  dev.enable = true;

};

##############################################################################
#
# System Services
#
##############################################################################

services.dbus.enable = true;

services.udisks2.enable = true;

services.gvfs.enable = true;

services.upower.enable = true;

##############################################################################
#
# End of Configuration
#
##############################################################################
