# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/Console" = {
      last-window-maximised = false;
      last-window-size = (lib.hm.gvariant.mkTuple [ 812 504 ]);
    };

  };
}
