# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "io/gitlab/adhami3310/Impression" = {
      is-maximized = false;
      window-height = 600;
      window-width = 500;
    };

    "org/gnome/GPaste" = {
      growing-lines = true;
      images-support = true;
      min-text-item-size = (lib.hm.gvariant.mkUint64 10);
      primary-to-history = true;
      synchronize-clipboards = true;
      track-changes = true;
      track-extension-state = true;
      trim-items = true;
    };

    "org/gnome/TextEditor" = {
      style-scheme = "stylix";
    };

    "org/gnome/eog/view" = {
      background-color = "#dde1fa";
    };

    "org/gnome/papers" = {
      night-mode = false;
    };

    "org/gnome/papers/default" = {
      annot-color = "yellow";
      continuous = true;
      dual-page = false;
      dual-page-odd-left = true;
      enable-spellchecking = true;
      eraser-mode-objects = "true";
      highlight-color = "yellow";
      highlight-stroke = 2.0;
      pen-color = "blue";
      pen-stroke = 1.0;
      show-sidebar = false;
      sizing-mode = "automatic";
      text-color = "blue";
      window-height = 1046;
      window-maximized = true;
      window-width = 600;
    };

    "org/gnome/tweaks" = {
      show-extensions-notice = false;
    };

  };
}
