# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/shell" = {
      app-picker-layout = [
        ([
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Contacts.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 0)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Weather.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 1)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.clocks.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 2)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Maps.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 3)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.SimpleScan.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 4)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Settings.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 5)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Showtime.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 6)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Snapshot.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 7)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Characters.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 8)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "Utilities"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 9)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "btop.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 10)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "System"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 11)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Calculator.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 12)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Tour.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 13)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Yelp.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 14)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "ca.desrt.dconf-editor.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 15)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "com.mattjakeman.ExtensionManager.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 16)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Extensions.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 17)
              ])
            ])
          ])
        ])
        ([
          (lib.hm.gvariant.mkDictionaryEntry [
            "gparted.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 0)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.GPaste.Ui.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 1)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.GPaste.Preferences.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 2)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "guvcview.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 3)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "htop.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 4)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "jellyfin-tui.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 5)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "lf.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 6)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "startcenter.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 7)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "base.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 8)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "calc.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 9)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "draw.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 10)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "impress.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 11)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "math.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 12)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "writer.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 13)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "cups.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 14)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "mpv.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 15)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "nvim.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 16)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "soundconverter.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 17)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "vim.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 18)
              ])
            ])
          ])
        ])
        ([
          (lib.hm.gvariant.mkDictionaryEntry [
            "ranger.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 0)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.tweaks.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 1)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "vlc.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 2)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.wireshark.Wireshark.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 3)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "xterm.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 4)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "yazi.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 5)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Epiphany.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 6)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Calendar.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 7)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.Music.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 8)
              ])
            ])
          ])
          (lib.hm.gvariant.mkDictionaryEntry [
            "org.gnome.TextEditor.desktop"
            (lib.hm.gvariant.mkVariant [
              (lib.hm.gvariant.mkDictionaryEntry [
                "position"
                (lib.hm.gvariant.mkVariant 9)
              ])
            ])
          ])
        ])
      ];
      disable-extension-version-validation = true;
      disable-user-extensions = false;
      disabled-extensions = [ ];
      enabled-extensions = [
        "appindicatorsupport@rgcjonas.gmail.com"
        "arcmenu@arcmenu.com"
        "blur-my-shell@aunetx"
        "dash-to-dock@micxgx.gmail.com"
        "dynamic-music-pill@andbal"
        "GPaste@gnome-shell-extensions.gnome.org"
        "notification-configurator@exposedcat"
        "pomodoro-timer@Oguzhankokulu.github.com"
        "quake-terminal@diegodario88.github.io"
        "quick-settings-audio-panel@rayzeq.github.io"
        "steal-my-focus-window@steal-my-focus-window"
        "Vitals@CoreCoding.com"
        "wallpicker@omarxkhalid.github.io"
        "modernclock@gnome-port"
        "user-theme@gnome-shell-extensions.gcampax.github.com"
        "openbar@neuromorph"
      ];
      favorite-apps = [
        "mullvad-vpn.desktop"
        "kitty.desktop"
        "terminator.desktop"
        "org.gnome.Console.desktop"
        "virt-manager.desktop"
        "org.gnome.Nautilus.desktop"
        "1password.desktop"
        "firefox.desktop"
        "chromium-browser.desktop"
        "joplin.desktop"
        "org.gnome.Evolution.desktop"
        "onlyoffice-desktopeditors.desktop"
        "element-desktop.desktop"
        "discord.desktop"
        "com.ktechpit.whatsie.desktop"
        "org.jellyfin.JellyfinDesktop.desktop"
        "de.haeckerfelix.Shortwave.desktop"
        "io.gitlab.adhami3310.Impression.desktop"
        "net.nokyan.Resources.desktop"
        "org.nickvision.tubeconverter.desktop"
        "org.qbittorrent.qBittorrent.desktop"
        "nixos-manual.desktop"
      ];
      last-selected-power-profile = "power-saver";
      welcome-dialog-last-shown-version = "50.1";
    };

    "org/gnome/shell/keybindings" = {
      focus-active-notification = [ "<Super>n" ];
      open-new-window-application-1 = [ "<Super><Control>1" ];
      open-new-window-application-2 = [ "<Super><Control>2" ];
      open-new-window-application-3 = [ "<Super><Control>3" ];
      open-new-window-application-4 = [ "<Super><Control>4" ];
      open-new-window-application-5 = [ "<Super><Control>5" ];
      open-new-window-application-6 = [ "<Super><Control>6" ];
      open-new-window-application-7 = [ "<Super><Control>7" ];
      open-new-window-application-8 = [ "<Super><Control>8" ];
      open-new-window-application-9 = [ "<Super><Control>9" ];
      screen-brightness-cycle = [ "XF86MonBrightnessCycle" ];
      screen-brightness-cycle-monitor = [ "<Shift>XF86MonBrightnessCycle" ];
      screen-brightness-down = [ "<Ctrl><Super>Down" ];
      screen-brightness-down-monitor = [ "<Shift>XF86MonBrightnessDown" ];
      screen-brightness-up = [ "<Ctrl><Super>Up" ];
      screen-brightness-up-monitor = [ "<Shift>XF86MonBrightnessUp" ];
      screenshot = [ "<Shift>Print" ];
      screenshot-window = [ "<Alt>Print" ];
      shift-overview-down = [ "<Super><Alt>Down" ];
      shift-overview-up = [ "<Super><Alt>Up" ];
      show-screen-recording-ui = [ "<Ctrl><Shift><Alt>R" ];
      show-screenshot-ui = [ "<Alt>F9" ];
      switch-to-application-1 = [ "<Super>1" ];
      switch-to-application-2 = [ "<Super>2" ];
      switch-to-application-3 = [ "<Super>3" ];
      switch-to-application-4 = [ "<Super>4" ];
      switch-to-application-5 = [ "<Super>5" ];
      switch-to-application-6 = [ "<Super>6" ];
      switch-to-application-7 = [ "<Super>7" ];
      switch-to-application-8 = [ "<Super>8" ];
      switch-to-application-9 = [ "<Super>9" ];
      toggle-application-view = [ "<Super>a" ];
      toggle-message-tray = [ "<Control>F2" ];
      toggle-overview = [ "<Control><Super>bracketleft" ];
      toggle-quick-settings = [ "<Control>F3" ];
    };

    "org/gnome/shell/weather" = {
      automatic-location = true;
      locations = [
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Rio de Janeiro"
                    "SBRJ"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.39968039870670141)
                          (-0.75340046626198298)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.39968039870670141)
                          (-0.75456400746111763)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
      ];
    };

    "org/gnome/shell/world-clocks" = {
      locations = [
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "London"
                    "EGWU"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.89971722940307675
                          (-0.007272211034407213)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.89884456477707964
                          (-0.0020362232784242244)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Port-of-Spain"
                    "TTPP"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.18529579473782881
                          (-1.0707594960985212)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.18587756533739611
                          (-1.0736683840029426)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Los Angeles"
                    "KHHR"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.59207870611576607
                          (-2.0652820330855488)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.59432360095955872
                          (-2.063741622941031)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "New York"
                    "KNYC"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.71180344078725644
                          (-1.2909618758762367)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.71059804659265924
                          (-1.2916478949920254)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Toronto"
                    "CYTZ"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.76154532446909495
                          (-1.3857914260834978)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.76212711252195475
                          (-1.3860823201099277)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Paris"
                    "LFPB"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.85462956287765413
                          0.042760566673861078
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.8528842336256599
                          0.040724343395436846
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Rio de Janeiro"
                    "SBRJ"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.39968039870670141)
                          (-0.75340046626198298)
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.39968039870670141)
                          (-0.75456400746111763)
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Sydney"
                    "YSSY"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.59253928105207498)
                          2.6386469349889961
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          (-0.59137572239964786)
                          2.6392287230418559
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Tokyo"
                    "RJTI"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.62191898430954862
                          2.4408429589140699
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.62282074357417661
                          2.4391218722853854
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
        (
          (lib.hm.gvariant.mkVariant (
            lib.hm.gvariant.mkTuple [
              ((lib.hm.gvariant.mkUint32 2))
              (
                (lib.hm.gvariant.mkVariant (
                  lib.hm.gvariant.mkTuple [
                    "Beijing"
                    "ZBAA"
                    true
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.69696814214530467
                          2.0295270260429752
                        ])
                      )
                    ])
                    ([
                      (
                        (lib.hm.gvariant.mkTuple [
                          0.69689057971334611
                          2.0313596217575696
                        ])
                      )
                    ])
                  ]
                ))
              )
            ]
          ))
        )
      ];
    };

  };
}
