# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/shell/extensions/appindicator" = {
      icon-brightness = 0.0;
      icon-contrast = 0.0;
      icon-opacity = 240;
      icon-saturation = 0.0;
      icon-size = 0;
      tray-pos = "left";
    };

    "org/gnome/shell/extensions/arcmenu" = {
      arcmenu-hotkey = [ "<Control>F1" ];
      arcmenu-hotkey-overlay-key-enabled = true;
      distro-icon = 22;
      hotkey-open-primary-monitor = false;
      left-panel-width = 190;
      menu-button-icon = "resource:///org/gnome/shell/extensions/arcmenu/icons/scalable/actions/distro-nixos-symbolic.svg";
      menu-item-icon-size = "Default";
      menu-layout = "Whisker";
      prefs-visible-page = 0;
      recently-installed-apps = [ ];
      runner-hotkey = [ "<Alt>space" ];
      runner-hotkey-open-primary-monitor = true;
      runner-hotkey-overlay-key-enabled = true;
      search-entry-border-radius = (
        lib.hm.gvariant.mkTuple [
          true
          25
        ]
      );
      show-category-sub-menus = true;
      update-notifier-project-version = 73;
      vert-separator = true;
    };

    "org/gnome/shell/extensions/blur-my-shell" = {
      rounded-blur-found = false;
      settings-version = 2;
    };

    "org/gnome/shell/extensions/blur-my-shell/appfolder" = {
      brightness = 0.59999999999999998;
      sigma = 30;
    };

    "org/gnome/shell/extensions/blur-my-shell/applications" = {
      blur = true;
      dynamic-opacity = true;
      enable-all = true;
      opacity = 241;
      pipeline = "pipeline_default";
      static-blur = false;
    };

    "org/gnome/shell/extensions/blur-my-shell/coverflow-alt-tab" = {
      pipeline = "pipeline_default";
    };

    "org/gnome/shell/extensions/blur-my-shell/dash-to-dock" = {
      blur = false;
      brightness = 0.59999999999999998;
      pipeline = "pipeline_default_rounded";
      sigma = 30;
      static-blur = true;
      style-dash-to-dock = 0;
    };

    "org/gnome/shell/extensions/blur-my-shell/lockscreen" = {
      pipeline = "pipeline_default";
    };

    "org/gnome/shell/extensions/blur-my-shell/overview" = {
      pipeline = "pipeline_default";
    };

    "org/gnome/shell/extensions/blur-my-shell/panel" = {
      blur = false;
      brightness = 0.59999999999999998;
      corner-radius = 0;
      pipeline = "pipeline_default";
      sigma = 30;
    };

    "org/gnome/shell/extensions/blur-my-shell/screenshot" = {
      pipeline = "pipeline_default";
    };

    "org/gnome/shell/extensions/blur-my-shell/window-list" = {
      brightness = 0.59999999999999998;
      sigma = 30;
    };

    "org/gnome/shell/extensions/dash-to-dock" = {
      apply-custom-theme = true;
      background-opacity = 0.80000000000000004;
      custom-theme-shrink = true;
      customize-alphas = true;
      dash-max-icon-size = 48;
      disable-overview-on-startup = true;
      dock-position = "BOTTOM";
      extend-height = false;
      height-fraction = 0.90000000000000002;
      icon-size-fixed = false;
      max-alpha = 0.94999999999999996;
      min-alpha = 0.46999999999999997;
      preferred-monitor = (-2);
      preferred-monitor-by-connector = "DP-1";
      transparency-mode = "DYNAMIC";
    };

    "org/gnome/shell/extensions/ddcbrightness" = {
      brightness-down = [ "<Alt><Shift>F1" ];
      brightness-up = [ "<Alt><Shift>F2" ];
      link-displays = true;
    };

    "org/gnome/shell/extensions/display-brightness-ddcutil" = {
      ddcutil-binary-path = "/nix/store/p1i2shr6khp64py5za6xa8l74a9nkcf1-ddcutil-2.2.7/bin/ddcutil";
      ddcutil-sleep-multiplier = 40.0;
      decrease-brightness-shortcut = [ "<Alt><Super>F3" ];
      increase-brightness-shortcut = [ "<Alt><Super>F4" ];
      only-all-slider = true;
      position-system-menu = 3.0;
      show-all-slider = true;
      show-display-name = true;
      show-internal-slider = true;
      show-osd = true;
      show-value-label = true;
      step-change-keyboard = 2.0;
    };

    "org/gnome/shell/extensions/dynamic-music-pill" = {
      enable-shadow = true;
      enable-transparency = true;
      has-seen-first-hint = true;
      horizontal-offset = (-13);
      panel-pill-height = 26;
      popup-custom-width = 360;
      popup-show-visualizer = true;
      popup-visualizer-bars = 30;
      shadow-blur = 13;
      shadow-opacity = 65;
      sync-accent-color = true;
      target-container = 2;
      transparency-strength = 0;
      transparency-text = false;
      transparency-vis = false;
      vertical-offset = 1;
      visualizer-bars = 30;
      visualizer-style = 3;
    };

    "org/gnome/shell/extensions/libpanel" = {
      layout = [
        ([
          "gnome@main"
          "quick-settings-audio-panel@rayzeq.github.io/main"
          "[EMAIL]/main"
        ])
      ];
    };

    "org/gnome/shell/extensions/notification-configurator" = {
      global = "{\"enabled\":true,\"notificationCenter\":{\"disableGrouping\":false,\"maximumPerSource\":10},\"rateLimiting\":{\"enabled\":true,\"notificationThreshold\":5000,\"action\":\"close\"},\"timeout\":{\"enabled\":true,\"notificationTimeout\":2000,\"ignoreIdle\":true},\"urgency\":{\"alwaysNormalUrgency\":false},\"display\":{\"enableFullscreen\":false,\"notificationPosition\":\"right\",\"verticalPosition\":\"top\",\"hideAppTitleRow\":false},\"colors\":{\"enabled\":true,\"theme\":{\"appNameColor\":[0.6,0.6,0.607843137,1],\"timeColor\":[0.6,0.6,0.607843137,1],\"backgroundColor\":[0.329411765,0.329411765,0.352941176,1],\"titleColor\":[0.992156863,0.992156863,0.992156863,1],\"bodyColor\":[0.992156863,0.992156863,0.992156863,1],\"appNameFontSize\":11,\"timeFontSize\":10,\"titleFontSize\":11,\"bodyFontSize\":12}},\"margins\":{\"enabled\":false,\"top\":0,\"bottom\":0,\"left\":0,\"right\":0},\"windowAttention\":{\"activateInstead\":false}}";
    };

    "org/gnome/shell/extensions/openbar" = {
      accent-color = [
        "0"
        "0.75"
        "0.75"
      ];
      accent-override = false;
      apply-accent-shell = true;
      apply-all-shell = true;
      apply-flatpak = true;
      apply-gtk = true;
      apply-menu-notif = true;
      apply-menu-shell = true;
      auto-bgalpha = true;
      autofg-bar = true;
      autofg-menu = true;
      autohg-bar = true;
      autohg-menu = true;
      autotheme-dark = "Color";
      autotheme-font = true;
      autotheme-light = "Color";
      autotheme-refresh = true;
      balpha = 0.84999999999999998;
      bartype = "Trilands";
      bcolor = [
        "0.827"
        "0.749"
        "0.839"
      ];
      bg-change = true;
      bgalpha = 0.0;
      bgalpha-wmax = 1.0;
      bgalpha2 = 0.69999999999999996;
      bgcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      bgcolor-wmax = [
        "0.180"
        "0.180"
        "0.196"
      ];
      bgcolor2 = [
        "0.106"
        "0.110"
        "0.173"
      ];
      bgpalette = false;
      bguri = "file:///home/stefan-hacks/Pictures/wallpapers/Catppuccin_Mocha/17._Catppuccin_Mocha.jpg";
      border-wmax = false;
      bordertype = "solid";
      bottom-margin = 0.0;
      boxalpha = 0.0;
      boxcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      bradius = 30.0;
      buttonbg-wmax = true;
      bwidth = 1.0;
      candy1 = [
        "0"
        "0.61"
        "0.74"
      ];
      candy10 = [
        "0.09"
        "0.19"
        "0.72"
      ];
      candy11 = [
        "0.75"
        "0.49"
        "0.44"
      ];
      candy12 = [
        "1"
        "0.92"
        "0.12"
      ];
      candy13 = [
        "0.38"
        "0.63"
        "0.92"
      ];
      candy14 = [
        "0.37"
        "0.36"
        "0.39"
      ];
      candy15 = [
        "0.40"
        "0.23"
        "0.72"
      ];
      candy16 = [
        "1"
        "0.32"
        "0.32"
      ];
      candy2 = [
        "1"
        "0.41"
        "0.41"
      ];
      candy3 = [
        "0.63"
        "0.16"
        "0.8"
      ];
      candy4 = [
        "0.94"
        "0.60"
        "0.23"
      ];
      candy5 = [
        "0.03"
        "0.41"
        "0.62"
      ];
      candy6 = [
        "0.56"
        "0.18"
        "0.43"
      ];
      candy7 = [
        "0.95"
        "0.12"
        "0.67"
      ];
      candy8 = [
        "0.18"
        "0.76"
        "0.49"
      ];
      candy9 = [
        "0.93"
        "0.20"
        "0.23"
      ];
      candyalpha = 0.98999999999999999;
      candybar = false;
      card-hint = 30;
      color-scheme = "prefer-dark";
      corner-radius = false;
      count1 = 286179;
      count10 = 509;
      count11 = 441;
      count12 = 320;
      count2 = 116319;
      count3 = 53908;
      count4 = 53893;
      count5 = 38335;
      count6 = 5155;
      count7 = 4735;
      count8 = 1332;
      count9 = 874;
      cust-margin-wmax = false;
      dark-accent-color = [
        "0"
        "0.75"
        "0.75"
      ];
      dark-bcolor = [
        "0.827"
        "0.749"
        "0.839"
      ];
      dark-bgcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      dark-bgcolor-wmax = [
        "0.180"
        "0.180"
        "0.196"
      ];
      dark-bgcolor2 = [
        "0.106"
        "0.110"
        "0.173"
      ];
      dark-bguri = "file:///home/stefan-hacks/Pictures/wallpapers/Catppuccin_Mocha/17._Catppuccin_Mocha.jpg";
      dark-boxcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      dark-candy1 = [
        "0"
        "0.61"
        "0.74"
      ];
      dark-candy10 = [
        "0.09"
        "0.19"
        "0.72"
      ];
      dark-candy11 = [
        "0.75"
        "0.49"
        "0.44"
      ];
      dark-candy12 = [
        "1"
        "0.92"
        "0.12"
      ];
      dark-candy13 = [
        "0.38"
        "0.63"
        "0.92"
      ];
      dark-candy14 = [
        "0.37"
        "0.36"
        "0.39"
      ];
      dark-candy15 = [
        "0.40"
        "0.23"
        "0.72"
      ];
      dark-candy16 = [
        "1"
        "0.32"
        "0.32"
      ];
      dark-candy2 = [
        "1"
        "0.41"
        "0.41"
      ];
      dark-candy3 = [
        "0.63"
        "0.16"
        "0.8"
      ];
      dark-candy4 = [
        "0.94"
        "0.60"
        "0.23"
      ];
      dark-candy5 = [
        "0.03"
        "0.41"
        "0.62"
      ];
      dark-candy6 = [
        "0.56"
        "0.18"
        "0.43"
      ];
      dark-candy7 = [
        "0.95"
        "0.12"
        "0.67"
      ];
      dark-candy8 = [
        "0.18"
        "0.76"
        "0.49"
      ];
      dark-candy9 = [
        "0.93"
        "0.20"
        "0.23"
      ];
      dark-dbgcolor = [
        "0.125"
        "0.125"
        "0.125"
      ];
      dark-fgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      dark-hcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      dark-hscd-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      dark-iscolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      dark-mbcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      dark-mbgcolor = [
        "0.106"
        "0.106"
        "0.137"
      ];
      dark-mfgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      dark-mhcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      dark-mscolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      dark-mshcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      dark-palette1 = [
        "83"
        "82"
        "103"
      ];
      dark-palette10 = [
        "51"
        "54"
        "76"
      ];
      dark-palette11 = [
        "102"
        "106"
        "133"
      ];
      dark-palette12 = [
        "101"
        "123"
        "148"
      ];
      dark-palette2 = [
        "27"
        "28"
        "44"
      ];
      dark-palette3 = [
        "27"
        "27"
        "35"
      ];
      dark-palette4 = [
        "47"
        "46"
        "60"
      ];
      dark-palette5 = [
        "36"
        "35"
        "48"
      ];
      dark-palette6 = [
        "131"
        "123"
        "143"
      ];
      dark-palette7 = [
        "211"
        "191"
        "214"
      ];
      dark-palette8 = [
        "146"
        "191"
        "229"
      ];
      dark-palette9 = [
        "136"
        "148"
        "180"
      ];
      dark-shcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      dark-smbgcolor = [
        "0.106"
        "0.110"
        "0.173"
      ];
      dark-vw-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      dark-winbcolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      dashdock-style = "Bar";
      dbgalpha = 0.93000000000000005;
      dbgcolor = [
        "0.125"
        "0.125"
        "0.125"
      ];
      dborder = true;
      dbradius = 100.0;
      default-font = "Sans 12";
      destruct-color = [
        "0.75"
        "0.11"
        "0.16"
      ];
      disize = 48.0;
      dshadow = false;
      fgalpha = 1.0;
      fgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      fitts-widgets = true;
      font = "";
      gradient = false;
      gradient-direction = "vertical";
      gtk-popover = true;
      gtk-shadow = "Default";
      gtk-transparency = 1.0;
      halpha = 0.5;
      handle-border = 3.0;
      hbar-gtk3only = true;
      hcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      headerbar-hint = 30;
      heffect = false;
      height = 34.0;
      hpad = 1.0;
      hscd-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      import-export = false;
      isalpha = 0.94999999999999996;
      iscolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      light-accent-color = [
        "0"
        "0.75"
        "0.75"
      ];
      light-bcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      light-bgcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      light-bgcolor-wmax = [
        "0.745"
        "0.745"
        "0.761"
      ];
      light-bgcolor2 = [
        "0.106"
        "0.110"
        "0.173"
      ];
      light-bguri = "file:///home/stefan-hacks/Pictures/wallpapers/Catppuccin_Mocha/17._Catppuccin_Mocha.jpg";
      light-boxcolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      light-candy1 = [
        "0"
        "0.61"
        "0.74"
      ];
      light-candy10 = [
        "0.09"
        "0.19"
        "0.72"
      ];
      light-candy11 = [
        "0.75"
        "0.49"
        "0.44"
      ];
      light-candy12 = [
        "1"
        "0.92"
        "0.12"
      ];
      light-candy13 = [
        "0.38"
        "0.63"
        "0.92"
      ];
      light-candy14 = [
        "0.37"
        "0.36"
        "0.39"
      ];
      light-candy15 = [
        "0.40"
        "0.23"
        "0.72"
      ];
      light-candy16 = [
        "1"
        "0.32"
        "0.32"
      ];
      light-candy2 = [
        "1"
        "0.41"
        "0.41"
      ];
      light-candy3 = [
        "0.63"
        "0.16"
        "0.8"
      ];
      light-candy4 = [
        "0.94"
        "0.60"
        "0.23"
      ];
      light-candy5 = [
        "0.03"
        "0.41"
        "0.62"
      ];
      light-candy6 = [
        "0.56"
        "0.18"
        "0.43"
      ];
      light-candy7 = [
        "0.95"
        "0.12"
        "0.67"
      ];
      light-candy8 = [
        "0.18"
        "0.76"
        "0.49"
      ];
      light-candy9 = [
        "0.93"
        "0.20"
        "0.23"
      ];
      light-dbgcolor = [
        "0.125"
        "0.125"
        "0.125"
      ];
      light-fgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      light-hcolor = [
        "0.184"
        "0.180"
        "0.235"
      ];
      light-hscd-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      light-iscolor = [
        "0.141"
        "0.137"
        "0.188"
      ];
      light-mbcolor = [
        "0.184"
        "0.180"
        "0.235"
      ];
      light-mbgcolor = [
        "0.106"
        "0.106"
        "0.137"
      ];
      light-mfgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      light-mhcolor = [
        "0.184"
        "0.180"
        "0.235"
      ];
      light-mscolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      light-mshcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      light-palette1 = [
        "83"
        "82"
        "103"
      ];
      light-palette10 = [
        "51"
        "54"
        "76"
      ];
      light-palette11 = [
        "102"
        "106"
        "133"
      ];
      light-palette12 = [
        "101"
        "123"
        "148"
      ];
      light-palette2 = [
        "27"
        "28"
        "44"
      ];
      light-palette3 = [
        "27"
        "27"
        "35"
      ];
      light-palette4 = [
        "47"
        "46"
        "60"
      ];
      light-palette5 = [
        "36"
        "35"
        "48"
      ];
      light-palette6 = [
        "131"
        "123"
        "143"
      ];
      light-palette7 = [
        "211"
        "191"
        "214"
      ];
      light-palette8 = [
        "146"
        "191"
        "229"
      ];
      light-palette9 = [
        "136"
        "148"
        "180"
      ];
      light-shcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      light-smbgcolor = [
        "0.106"
        "0.110"
        "0.173"
      ];
      light-vw-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      light-winbcolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      margin = 0.0;
      margin-wmax = 2.0;
      mbalpha = 0.59999999999999998;
      mbcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      mbg-gradient = false;
      mbgalpha = 0.94999999999999996;
      mbgcolor = [
        "0.106"
        "0.106"
        "0.137"
      ];
      menu-radius = 21.0;
      menustyle = true;
      mfgalpha = 1.0;
      mfgcolor = [
        "1.0"
        "1.0"
        "1.0"
      ];
      mhalpha = 0.29999999999999999;
      mhcolor = [
        "0.573"
        "0.749"
        "0.898"
      ];
      monitor-height = 1080;
      monitor-width = 1920;
      monitors = "all";
      msalpha = 0.84999999999999998;
      mscolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      mshalpha = 0.16;
      mshcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      neon = false;
      neon-wmax = false;
      notif-radius = 10.0;
      palette1 = [
        "83"
        "82"
        "103"
      ];
      palette10 = [
        "51"
        "54"
        "76"
      ];
      palette11 = [
        "102"
        "106"
        "133"
      ];
      palette12 = [
        "101"
        "123"
        "148"
      ];
      palette2 = [
        "27"
        "28"
        "44"
      ];
      palette3 = [
        "27"
        "27"
        "35"
      ];
      palette4 = [
        "47"
        "46"
        "60"
      ];
      palette5 = [
        "36"
        "35"
        "48"
      ];
      palette6 = [
        "131"
        "123"
        "143"
      ];
      palette7 = [
        "211"
        "191"
        "214"
      ];
      palette8 = [
        "146"
        "191"
        "229"
      ];
      palette9 = [
        "136"
        "148"
        "180"
      ];
      pause-reload = false;
      position = "Top";
      prominent1 = [
        "100"
        "100"
        "100"
      ];
      prominent2 = [
        "100"
        "100"
        "100"
      ];
      prominent3 = [
        "100"
        "100"
        "100"
      ];
      prominent4 = [
        "100"
        "100"
        "100"
      ];
      prominent5 = [
        "100"
        "100"
        "100"
      ];
      prominent6 = [
        "100"
        "100"
        "100"
      ];
      qtoggle-radius = 50.0;
      radius-bottomleft = true;
      radius-bottomright = true;
      radius-topleft = true;
      radius-topright = true;
      reloadstyle = false;
      removestyle = false;
      sbar-gradient = "none";
      set-bottom-margin = false;
      set-fullscreen = true;
      set-notif-position = false;
      set-notifications = false;
      set-overview = false;
      set-yarutheme = true;
      shadow = false;
      shalpha = 0.20000000000000001;
      shcolor = [
        "0.000"
        "0.000"
        "0.000"
      ];
      sidebar-hint = 30;
      slider-height = 4.0;
      smbgalpha = 0.94999999999999996;
      smbgcolor = [
        "0.106"
        "0.110"
        "0.173"
      ];
      smbgoverride = true;
      success-color = [
        "0.15"
        "0.635"
        "0.41"
      ];
      traffic-light = false;
      trigger-autotheme = false;
      trigger-reload = false;
      view-hint = 20;
      vpad = 4.0;
      vw-color = [
        "0.333"
        "0.333"
        "0.388"
      ];
      warning-color = [
        "0.96"
        "0.83"
        "0.17"
      ];
      width-bottom = true;
      width-left = true;
      width-right = true;
      width-top = true;
      winbalpha = 0.75;
      winbcolor = [
        "0.333"
        "0.333"
        "0.388"
      ];
      winbradius = 15.0;
      winbwidth = 0.0;
      window-hint = 20;
      wmax-hbarhint = false;
      wmaxbar = false;
    };

    "org/gnome/shell/extensions/pomodoro-timer" = {
      focus-saved-event-sounds = "";
      focus-saved-show-banners = "";
      focus-saved-wallpaper-uri = "";
      focus-saved-wallpaper-uri-dark = "";
      session-completed-intervals = 3;
      session-interval-type = "work";
      session-remaining-time = 1500;
      session-started = true;
      session-state = "idle";
    };

    "org/gnome/shell/extensions/quake-terminal" = {
      always-on-top = true;
      animation-time = 0;
      auto-hide-window = false;
      horizontal-size = 95;
      render-on-primary-monitor = true;
      terminal-id = "kitty.desktop";
      terminal-shortcut = [ "<Control><Alt>q" ];
      vertical-size = 95;
    };

    "org/gnome/shell/extensions/quick-settings-audio-panel" = {
      profiles-renames = [
        (lib.hm.gvariant.mkDictionaryEntry [
          "500 Series Chipset Family On-Package High Definition Audio (HD Audio)"
          [
            (lib.hm.gvariant.mkDictionaryEntry [
              "off"
              (lib.hm.gvariant.mkTuple [
                "Off"
                "Off"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "pro-audio"
              (lib.hm.gvariant.mkTuple [
                "Pro Audio"
                "Pro Audio"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "HiFi (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)"
              (lib.hm.gvariant.mkTuple [
                "Play HiFi quality Music (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)"
                "Play HiFi quality Music (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "HiFi (HDMI1, HDMI2, HDMI3, Headphones, Mic1, Mic2)"
              (lib.hm.gvariant.mkTuple [
                "Play HiFi quality Music (HDMI1, HDMI2, HDMI3, Headphones, Mic1, Mic2)"
                "Play HiFi quality Music (HDMI1, HDMI2, HDMI3, Headphones, Mic1, Mic2)"
              ])
            ])
          ]
        ])
        (lib.hm.gvariant.mkDictionaryEntry [
          "HP DHE-8005U Audio Device"
          [
            (lib.hm.gvariant.mkDictionaryEntry [
              "off"
              (lib.hm.gvariant.mkTuple [
                "Off"
                "Off"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "input:mono-fallback"
              (lib.hm.gvariant.mkTuple [
                "Mono Input"
                "Mono Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "pro-audio"
              (lib.hm.gvariant.mkTuple [
                "Pro Audio"
                "Pro Audio"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Output"
                "Digital Stereo (IEC958) Output"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:iec958-stereo+input:mono-fallback"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Output + Mono Input"
                "Digital Stereo (IEC958) Output + Mono Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Output"
                "Analog Stereo Output"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:analog-stereo+input:mono-fallback"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Output + Mono Input"
                "Analog Stereo Output + Mono Input"
              ])
            ])
          ]
        ])
        (lib.hm.gvariant.mkDictionaryEntry [
          "Steren COM-126"
          [
            (lib.hm.gvariant.mkDictionaryEntry [
              "off"
              (lib.hm.gvariant.mkTuple [
                "Off"
                "Off"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "pro-audio"
              (lib.hm.gvariant.mkTuple [
                "Pro Audio"
                "Pro Audio"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "input:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Input"
                "Digital Stereo (IEC958) Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "input:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Input"
                "Analog Stereo Input"
              ])
            ])
          ]
        ])
        (lib.hm.gvariant.mkDictionaryEntry [
          "USB Audio"
          [
            (lib.hm.gvariant.mkDictionaryEntry [
              "off"
              (lib.hm.gvariant.mkTuple [
                "Off"
                "Off"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "pro-audio"
              (lib.hm.gvariant.mkTuple [
                "Pro Audio"
                "Pro Audio"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "input:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Input"
                "Digital Stereo (IEC958) Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "input:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Input"
                "Analog Stereo Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Output"
                "Digital Stereo (IEC958) Output"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:iec958-stereo+input:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo Duplex (IEC958)"
                "Digital Stereo Duplex (IEC958)"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:iec958-stereo+input:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Digital Stereo (IEC958) Output + Analog Stereo Input"
                "Digital Stereo (IEC958) Output + Analog Stereo Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Output"
                "Analog Stereo Output"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:analog-stereo+input:iec958-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Output + Digital Stereo (IEC958) Input"
                "Analog Stereo Output + Digital Stereo (IEC958) Input"
              ])
            ])
            (lib.hm.gvariant.mkDictionaryEntry [
              "output:analog-stereo+input:analog-stereo"
              (lib.hm.gvariant.mkTuple [
                "Analog Stereo Duplex"
                "Analog Stereo Duplex"
              ])
            ])
          ]
        ])
      ];
      version = 2;
    };

    "org/gnome/shell/extensions/user-theme" = {
      name = "Yaru-dark";
    };

    "org/gnome/shell/extensions/wallpicker" = {
      wall-dirs = [ "/home/stefan-hacks/Pictures/wallpapers" ];
    };

  };
}
