# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "net/nokyan/Resources" = {
      is-maximized = false;
      window-height = 900;
      window-width = 1024;
    };

  };
}
