# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/freedesktop/folks" = {
      primary-store = "eds:8cbd1af6916fc6784e30c425a5fa0ee5f0153aec";
    };

    "org/gnome/Contacts" = {
      did-initial-setup = true;
      window-fullscreen = false;
      window-height = 600;
      window-maximized = false;
      window-width = 800;
    };

    "org/gnome/evolution" = {
      default-address-book = "8cbd1af6916fc6784e30c425a5fa0ee5f0153aec";
      disabled-eplugins = [ "org.gnome.evolution.attachment-reminder" ];
      version = "3.60.2";
    };

    "org/gnome/evolution/addressbook" = {
      completion-minimum-query-length = 3;
      completion-show-address = false;
    };

    "org/gnome/evolution/calendar" = {
      week-start-day-name = "monday";
      work-day-friday = true;
      work-day-monday = true;
      work-day-saturday = false;
      work-day-sunday = false;
      work-day-thursday = true;
      work-day-tuesday = true;
      work-day-wednesday = true;
    };

    "org/gnome/evolution/mail" = {
      browser-close-on-reply-policy = "ask";
      composer-visually-wrap-long-lines = false;
      forward-style-name = "attached";
      image-loading-policy = "never";
      message-list-sort-on-header-click = "always";
      paned-size = 1562785;
      prompt-check-if-default-mailer = false;
      reply-style-name = "quoted";
      to-do-bar-width = 1150000;
    };

    "org/gnome/evolution/mail/composer-window" = {
      height = 500;
      maximized = true;
      width = 600;
    };

    "org/gnome/evolution/shell" = {
      default-component-id = "mail";
    };

    "org/gnome/evolution/shell/window" = {
      height = 900;
      maximized = true;
      width = 1440;
      x = 0;
      y = 0;
    };

  };
}
