# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/desktop/background" = {
      color-shading-type = "solid";
      picture-options = "zoom";
      picture-uri = "file:///home/stefan-hacks/Pictures/wallpapers/Catppuccin_Mocha/17._Catppuccin_Mocha.jpg";
      picture-uri-dark = "file:///home/stefan-hacks/Pictures/wallpapers/Catppuccin_Mocha/17._Catppuccin_Mocha.jpg";
    };

    "org/gnome/desktop/interface" = {
      accent-color = "red";
      clock-format = "12h";
      clock-show-weekday = true;
      color-scheme = "prefer-dark";
      cursor-blink = true;
      cursor-blink-time = 1000;
      cursor-size = 24;
      cursor-theme = "Adwaita";
      document-font-name = "JetBrainsMono Nerd Font Thin 10";
      enable-animations = true;
      font-name = "JetBrainsMono Nerd Font Thin 10";
      gtk-theme = "Yaru-blue-dark";
      icon-theme = "Yaru-blue-dark";
      monospace-font-name = "JetBrainsMono Nerd Font Thin 10";
      scaling-factor = (lib.hm.gvariant.mkUint32 1);
      show-battery-percentage = true;
      text-scaling-factor = 1.0;
      toolbar-style = "text";
      toolkit-accessibility = false;
    };

    "org/gnome/desktop/session" = {
      idle-delay = (lib.hm.gvariant.mkUint32 900);
    };

    "org/gnome/desktop/sound" = {
      allow-volume-above-100-percent = true;
      event-sounds = true;
      theme-name = "ocean";
    };

    "org/gtk/gtk4/settings/color-chooser" = {
      selected-color = (
        lib.hm.gvariant.mkTuple [
          true
          1.0
          1.0
          1.0
          1.0
        ]
      );
    };

    "org/gtk/gtk4/settings/file-chooser" = {
      date-format = "regular";
      location-mode = "path-bar";
      show-hidden = true;
      sidebar-width = 140;
      sort-column = "name";
      sort-directories-first = true;
      sort-order = "ascending";
      type-format = "category";
      view-type = "list";
      window-size = (
        lib.hm.gvariant.mkTuple [
          815
          326
        ]
      );
    };

    "org/gtk/settings/color-chooser" = {
      selected-color = (
        lib.hm.gvariant.mkTuple [
          true
          0.0
          0.0
          0.0
          1.0
        ]
      );
    };

    "org/gtk/settings/file-chooser" = {
      clock-format = "12h";
      date-format = "regular";
      location-mode = "path-bar";
      show-hidden = false;
      show-size-column = true;
      show-type-column = true;
      sidebar-width = 174;
      sort-column = "name";
      sort-directories-first = false;
      sort-order = "ascending";
      type-format = "category";
      window-position = (
        lib.hm.gvariant.mkTuple [
          2558
          48
        ]
      );
      window-size = (
        lib.hm.gvariant.mkTuple [
          1203
          786
        ]
      );
    };

  };
}
