# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "desktop/ibus/panel/emoji" = {
      favorites = [ "☢" ];
    };

    "org/gnome/desktop/input-sources" = {
      mru-sources = [
        (
          (lib.hm.gvariant.mkTuple [
            "xkb"
            "us"
          ])
        )
        (
          (lib.hm.gvariant.mkTuple [
            "xkb"
            "gb"
          ])
        )
      ];
      sources = [
        (
          (lib.hm.gvariant.mkTuple [
            "xkb"
            "us"
          ])
        )
      ];
      xkb-options = [ ];
    };

    "org/gnome/desktop/peripherals/mouse" = {
      natural-scroll = true;
      speed = 1.0;
    };

    "org/gnome/desktop/peripherals/pointingstick" = {
      speed = 1.0;
    };

    "org/gnome/desktop/peripherals/touchpad" = {
      speed = 1.0;
      two-finger-scrolling-enabled = true;
    };

  };
}
