# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/desktop/notifications" = {
      application-children = [ "firefox" "org-gnome-console" "gnome-about-panel" "discord" "org-gnome-evolution" "gnome-power-panel" "org-gnome-evolution-alarm-notify" "kitty" "virt-manager" "org-qbittorrent-qbittorrent" "mullvad-vpn" "com-ktechpit-whatsie" "org-gnome-nautilus" "joplin" "org-gnome-shell-extensions" "org-nickvision-tubeconverter" "de-haeckerfelix-shortwave" ];
      show-banners = true;
    };

    "org/gnome/desktop/notifications/application/1password" = {
      application-id = "1password.desktop";
    };

    "org/gnome/desktop/notifications/application/com-ktechpit-whatsie" = {
      application-id = "com.ktechpit.whatsie.desktop";
    };

    "org/gnome/desktop/notifications/application/de-haeckerfelix-shortwave" = {
      application-id = "de.haeckerfelix.Shortwave.desktop";
    };

    "org/gnome/desktop/notifications/application/discord" = {
      application-id = "discord.desktop";
    };

    "org/gnome/desktop/notifications/application/firefox" = {
      application-id = "firefox.desktop";
    };

    "org/gnome/desktop/notifications/application/gnome-about-panel" = {
      application-id = "gnome-about-panel.desktop";
    };

    "org/gnome/desktop/notifications/application/gnome-power-panel" = {
      application-id = "gnome-power-panel.desktop";
    };

    "org/gnome/desktop/notifications/application/joplin" = {
      application-id = "joplin.desktop";
    };

    "org/gnome/desktop/notifications/application/kitty" = {
      application-id = "kitty.desktop";
    };

    "org/gnome/desktop/notifications/application/mullvad-vpn" = {
      application-id = "mullvad-vpn.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-console" = {
      application-id = "org.gnome.Console.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-evolution-alarm-notify" = {
      application-id = "org.gnome.Evolution-alarm-notify.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-evolution" = {
      application-id = "org.gnome.Evolution.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-loupe" = {
      application-id = "org.gnome.Loupe.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-nautilus" = {
      application-id = "org.gnome.Nautilus.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-shell-extensions" = {
      application-id = "org.gnome.Shell.Extensions.desktop";
    };

    "org/gnome/desktop/notifications/application/org-gnome-texteditor" = {
      application-id = "org.gnome.TextEditor.desktop";
    };

    "org/gnome/desktop/notifications/application/org-nickvision-tubeconverter" = {
      application-id = "org.nickvision.tubeconverter.desktop";
    };

    "org/gnome/desktop/notifications/application/org-qbittorrent-qbittorrent" = {
      application-id = "org.qbittorrent.qBittorrent.desktop";
    };

    "org/gnome/desktop/notifications/application/virt-manager" = {
      application-id = "virt-manager.desktop";
    };

    "org/gnome/desktop/notifications/application/vlc" = {
      application-id = "vlc.desktop";
    };

  };
}
