# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/control-center" = {
      last-panel = "online-accounts";
      window-state = (
        lib.hm.gvariant.mkTuple [
          980
          640
          false
        ]
      );
    };

    "org/gnome/portal/filechooser/app-desktop" = {
      last-folder-path = "/home/stefan-hacks/Downloads";
    };

    "org/gnome/portal/filechooser/discord" = {
      last-folder-path = "/home/stefan-hacks/Documents/resume";
    };

    "org/gnome/portal/filechooser/element" = {
      last-folder-path = "/home/stefan-hacks/Documents";
    };

    "org/gnome/portal/filechooser/firefox" = {
      last-folder-path = "/home/stefan-hacks/Downloads";
    };

    "org/gnome/portal/filechooser/io.gitlab.adhami3310.Impression" = {
      last-folder-path = "/home/stefan-hacks/distro_images";
    };

    "org/gnome/portal/filechooser/org.gnome.Nautilus" = {
      last-folder-path = "/home/stefan-hacks/.config/nixit/assets";
    };

    "org/gnome/portal/filechooser/org.gnome.Settings" = {
      last-folder-path = "/home/stefan-hacks/.config/nixit/assets";
    };

    "org/gnome/settings-daemon/plugins/color" = {
      night-light-schedule-automatic = false;
    };

    "org/gnome/settings-daemon/plugins/housekeeping" = {
      donation-reminder-last-shown = (lib.hm.gvariant.mkInt64 1785169314187520);
    };

    "org/gnome/settings-daemon/plugins/media-keys" = {
      control-center = [ "<Alt><Super>period" ];
      email = [ "<Alt><Super>e" ];
      home = [ "<Alt><Super>h" ];
      mic-mute = [ "<Alt>F8" ];
      next = [ "<Control><Super>period" ];
      play = [ "<Control><Super>slash" ];
      previous = [ "<Control><Super>comma" ];
      screensaver = [ "<Control><Alt><Super>l" ];
      volume-down = [ "<Alt>F6" ];
      volume-mute = [ "<Alt>F5" ];
      volume-up = [ "<Alt>F7" ];
      www = [ "<Alt><Super>b" ];
    };

    "org/gnome/settings-daemon/plugins/power" = {
      power-button-action = "interactive";
      sleep-inactive-ac-timeout = 1200;
    };

  };
}
