# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ ... }:

{
  imports = [
    ./accessibility.nix
    ./app-folders.nix
    ./evolution.nix
    ./gtk.nix
    ./input-devices.nix
    ./media.nix
    ./misc.nix
    ./misc-apps.nix
    ./mutter.nix
    ./nautilus.nix
    ./notifications.nix
    ./settings-daemon.nix
    ./shell.nix
    ./shell-extensions.nix
    ./system-monitor.nix
    ./virt-manager.nix
    ./window-manager.nix
  ];
}
