# Generated by nix-my-gnome (nmg) -- https://github.com/stefan-hacks/nix-my-gnome
# Do not hand-edit generated sections; re-run nmg against a fresh dconf dump instead.

{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/desktop/wm/keybindings" = {
      activate-window-menu = [ ];
      begin-move = [ ];
      begin-resize = [ ];
      close = [ "<Alt>F4" ];
      cycle-group = [ ];
      cycle-group-backward = [ ];
      cycle-panels = [ "<Control><Alt>Escape" ];
      cycle-panels-backward = [ "<Shift><Control><Alt>Escape" ];
      cycle-windows = [ "<Alt>Escape" ];
      cycle-windows-backward = [ "<Shift><Alt>Escape" ];
      lower = [ "<Control><Super>g" ];
      maximize = [ "<Super>Up" ];
      maximize-horizontally = [ "<Control><Super>semicolon" ];
      maximize-vertically = [ "<Control><Super>apostrophe" ];
      minimize = [ "<Super>h" ];
      move-to-center = [ "<Control><Super>d" ];
      move-to-corner-ne = [ "<Control><Super>w" ];
      move-to-corner-nw = [ "<Control><Super>q" ];
      move-to-corner-se = [ "<Control><Super>s" ];
      move-to-corner-sw = [ "<Control><Super>a" ];
      move-to-monitor-down = [ "<Super><Shift>Down" ];
      move-to-monitor-left = [ "<Shift><Super>h" ];
      move-to-monitor-right = [ "<Shift><Super>l" ];
      move-to-monitor-up = [ "<Super><Shift>Up" ];
      move-to-side-e = [ "<Control><Super>o" ];
      move-to-side-n = [ "<Control><Super>e" ];
      move-to-side-s = [ "<Control><Super>i" ];
      move-to-side-w = [ "<Control><Super>p" ];
      move-to-workspace-1 = [ "<Super><Shift>Home" ];
      move-to-workspace-down = [ "<Control><Shift><Alt>Down" ];
      move-to-workspace-last = [ "<Super><Shift>End" ];
      move-to-workspace-left = [ "<Shift><Super>Page_Up" ];
      move-to-workspace-right = [ "<Shift><Super>Page_Down" ];
      move-to-workspace-up = [ "<Control><Shift><Alt>Up" ];
      panel-run-dialog = [ "<Alt>F2" ];
      raise = [ "<Control><Super>f" ];
      raise-or-lower = [ "<Control><Super>h" ];
      show-desktop = [ "<Control><Super>bracketright" ];
      switch-applications = [
        "<Super>Tab"
        "<Alt>Tab"
      ];
      switch-applications-backward = [
        "<Shift><Super>Tab"
        "<Shift><Alt>Tab"
      ];
      switch-group = [
        "<Super>Above_Tab"
        "<Alt>Above_Tab"
      ];
      switch-group-backward = [
        "<Shift><Super>Above_Tab"
        "<Shift><Alt>Above_Tab"
      ];
      switch-input-source = [
        "<Super>space"
        "XF86Keyboard"
      ];
      switch-input-source-backward = [
        "<Shift><Super>space"
        "<Shift>XF86Keyboard"
      ];
      switch-panels = [ "<Control><Alt>Tab" ];
      switch-panels-backward = [ "<Shift><Control><Alt>Tab" ];
      switch-to-workspace-1 = [ "<Alt><Super>1" ];
      switch-to-workspace-2 = [ "<Alt><Super>2" ];
      switch-to-workspace-3 = [ "<Alt><Super>3" ];
      switch-to-workspace-4 = [ "<Alt><Super>4" ];
      switch-to-workspace-5 = [ "<Alt><Super>5" ];
      switch-to-workspace-6 = [ "<Alt><Super>6" ];
      switch-to-workspace-7 = [ "<Alt><Super>7" ];
      switch-to-workspace-8 = [ "<Alt><Super>8" ];
      switch-to-workspace-9 = [ "<Alt><Super>9" ];
      switch-to-workspace-down = [ "<Control><Alt>Down" ];
      switch-to-workspace-last = [ "<Super>End" ];
      switch-to-workspace-left = [ "<Alt>F11" ];
      switch-to-workspace-right = [ "<Alt>F12" ];
      switch-to-workspace-up = [ "<Control><Alt>Up" ];
      toggle-above = [ "<Control><Super>k" ];
      toggle-fullscreen = [ "<Control><Super>j" ];
      toggle-maximized = [ "<Alt>F10" ];
      toggle-on-all-workspaces = [ "<Control><Super>l" ];
      unmaximize = [ "<Super>Down" ];
    };

    "org/gnome/desktop/wm/preferences" = {
      button-layout = "close,minimize,maximize:appmenu";
    };

  };
}
