# ============================================================================
# systems/ghost/default.nix
# ----------------------------------------------------------------------------
# Host definition for "ghost".  Declares the NixOS system configuration by
# selecting features (aspects) and composing them with the hardware profile.
#
# Dendritic principle: the host file ONLY selects features.  Feature
# definitions live in nixos/*.nix and are exported via
# inputs.self.nixosModules.*.
#
# Reference:
#   https://flake.parts
#   https://github.com/Doc-Steve/dendritic-design-with-flake-parts
# ============================================================================
{ inputs, ... }: {
  flake.nixosConfigurations.ghost = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    # Inject arguments that multiple feature modules need (avoids hard-coding
    # user names deep inside feature modules).
    specialArgs = {
      username = "stefan-hacks";
      usernames = [ "stefan-hacks" ];
      # ── Desktop Profile ────────────────────────────────────────────────────
      # Select the desktop environment.
      #   "gnome" → GNOME + GDM (default, safe)
      #   "dank"  → Niri + DankMaterialShell + dms-greeter (experimental)
      desktopProfile = "gnome";
      inherit inputs;
      inherit (inputs) nix-graph nixdr;
    };

    modules = [
      # ── Hardware Scan Target (generated by nixos-generate-config) ─────────
      ./hardware.nix

      # ── Host Identity & State Management ──────────────────────────────────
      {
        networking.hostName = "ghost";
        system.stateVersion = "26.05";
        nix.settings.experimental-features = [ "nix-command" "flakes" ];
        nixpkgs.config.allowUnfree = true;
      }

      # ── Unified Hardware Feature Profile Module ───────────────────────────
      ./elitebook.nix

      # ── Third-Party Extensible Aspects ────────────────────────────────────
      inputs.nixvim.nixosModules.nixvim
      inputs.self.nixosModules.terax

      # ── Local Feature Modules (Declarative Aspect Array) ──────────────────
      inputs.self.nixosModules.boot
      inputs.self.nixosModules.networking
      inputs.self.nixosModules.locale
      inputs.self.nixosModules.desktop # GNOME or DankMaterialShell (via desktopProfile)
      inputs.self.nixosModules.programs
      inputs.self.nixosModules.packages
      inputs.self.nixosModules.services
      inputs.self.nixosModules.user
      inputs.self.nixosModules.virtualization
      inputs.self.nixosModules.firewall
      inputs.self.nixosModules.fonts
      inputs.self.nixosModules.environment
      inputs.self.nixosModules.maintenance
      inputs.self.nixosModules.bluetooth
      inputs.self.nixosModules.kanata
      inputs.self.nixosModules.documentation
      inputs.self.nixosModules.home-manager
      inputs.self.nixosModules.network-tuning
      inputs.self.nixosModules.touchscreen
    ];
  };
}
