# ============================================================================
# systems/ghost/default.nix
# ----------------------------------------------------------------------------
# Host definition for "ghost".  Declares the NixOS system configuration by
# selecting features (aspects) and composing them with the hardware profile.
#
# Dendritic principle: the host file ONLY selects features.  Feature
# definitions live in nixos/*.nix and are exported via
# inputs.self.nixosModules.*.
#
# Reference:
#   https://flake.parts
#   https://github.com/Doc-Steve/dendritic-design-with-flake-parts
# ============================================================================
{ inputs, pkgs, ... }: {
  flake.nixosConfigurations.ghost = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    # Inject arguments that multiple feature modules need (avoids hard-coding
    # user names deep inside feature modules).
    specialArgs = {
      username = "stefan-hacks";
      usernames = [ "stefan-hacks" ];
      # ── Desktop Profile ────────────────────────────────────────────────────
      # Select the desktop environment.
      #   "gnome" → GNOME + GDM (default, safe)
      #   "dank"  → Niri + DankMaterialShell + dms-greeter (experimental)
      desktopProfile = "gnome";
      inherit inputs;
      inherit (inputs) nix-graph nixdr;
    };

    modules = [
      # ── Hardware (generated by nixos-generate-config) ─────────────────────
      ./hardware.nix

      # ── Host identity & state version ────────────────────────────────────
      {
        networking.hostName = "ghost";
        system.stateVersion = "26.05";

        nix.settings.experimental-features = [ "nix-command" "flakes" ];
        nixpkgs.config.allowUnfree = true;

        # ── Sound Open Firmware (SOF) for Intel Tiger Lake ────────────────────
        # The i5-1145G7 uses Intel Smart Sound Technology (SST) which needs
        # SOF firmware.  Without it the HDA driver falls back to a compatibility
        # mode with higher latency and occasional audio dropouts / crackling.
        hardware.firmware = with pkgs; [ sof-firmware ];

        # ── HP EliteBook 840 G8: Kernel Parameters ──────────────────────────
        # These fix NVMe stutter, USB dock stability, and audio issues specific
        # to this 11th-gen Intel (Tiger Lake) HP laptop.
        boot.kernelParams = [
          # Force SOF audio driver (SST) instead of legacy HDA fallback.
          # Prevents audio lag and dropouts on Tiger Lake.
          "snd_intel_dspcfg.dsp_driver=3"

          # Disable NVMe ACPI power management on the MAXIO MAP1202.
          # DRAM-less NVMe controllers stutter when APST aggressively transitions
          # power states under I/O load.
          "nvme.noacpi=1"

          # Disable USB autosuspend globally.
          # The HP USB-C Dock G5 (Realtek RTL8153 Ethernet + USB audio hub) drops
          # connection when Linux autosuspends USB devices.  Setting to -1
          # prevents the kernel from powering down USB ports.
          "usbcore.autosuspend=-1"

          # Explicitly set NVMe I/O scheduler to "none".
          # NVMe devices (especially DRAM-less controllers like the MAXIO MAP1202)
          # perform best with the blk-mq "none" scheduler.
          "elevator=none"
        ];

        # ── Graphics Drivers ──────────────────────────────────────────────────
        # Required for EGL/OpenGL support used by Electron apps (Mullvad GUI,
        # Discord, Chromium) and GNOME Shell compositing.
        #
        # Reference: https://nixos.wiki/wiki/OpenGL
        hardware.graphics.enable = true;
        hardware.graphics.extraPackages = with pkgs; [
          intel-media-driver  # VA-API for Intel Gen8+
          libvdpau-va-gl       # VDPAU → VA-API bridge
          intel-vaapi-driver   # Fallback for older GPUs
        ];

        # ── Firmware ──────────────────────────────────────────────────────────
        # Allow all proprietary firmware (Wi-Fi, GPU, Bluetooth, etc.) and
        # enable redistributable firmware so fwupd + microcode updates work
        # correctly.  Required for HP BIOS / firmware updates via `fwupdmgr`.
        hardware.enableAllFirmware = true;
      }

      # ── HP EliteBook 840 G8 Debian-equivalent modules ────────────────────
      # Host-specific kernel modules for Tiger Lake HP laptops.  Kept here
      # (not in hardware.nix) because hardware.nix is regenerated by
      # nixos-generate-config on fresh installs.
      ./elitebook.nix

      # ── NixOS features (order does not matter; NixOS modules are declarative)

      # ── Third-party modules ─────────────────────────────────────────────
      inputs.nixvim.nixosModules.nixvim
      inputs.self.nixosModules.terax

      # ── Local feature modules ──────────────────────────────────────────
      inputs.self.nixosModules.boot
      inputs.self.nixosModules.networking
      inputs.self.nixosModules.locale
      inputs.self.nixosModules.desktop # GNOME or DankMaterialShell (set via desktopProfile)
      inputs.self.nixosModules.programs
      inputs.self.nixosModules.packages
      inputs.self.nixosModules.services
      inputs.self.nixosModules.user
      inputs.self.nixosModules.virtualization
      inputs.self.nixosModules.firewall
      inputs.self.nixosModules.fonts
      inputs.self.nixosModules.environment
      inputs.self.nixosModules.maintenance
      inputs.self.nixosModules.bluetooth
      inputs.self.nixosModules.kanata
      inputs.self.nixosModules.documentation
      inputs.self.nixosModules.nixvim
      inputs.self.nixosModules.home-manager
      inputs.self.nixosModules.network-tuning
      inputs.self.nixosModules.touchscreen
    ];
  };
}
