# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"

    # ── HP EliteBook 840 G8 platform drivers ─────────────────────────────────
    # These modules are auto-loaded on Debian/Fedora but may not bind
    # automatically on NixOS.  Explicit loading ensures hotkeys, thermal
    # management, and platform features work correctly on Tiger Lake HP laptops.
    "hp_wmi"                   # HP WMI interface: hotkeys, radio switch, platform profile
    "hp_bioscfg"               # HP BIOS configuration access
    "intel_hid"                # Intel HID events: sleep button, special keys
    "processor_thermal_device" # CPU thermal management (loads processor_thermal_* sub-modules)
    "x86_pkg_temp_thermal"     # CPU temperature sensor

    # ── Intel Audio Virtualization ──────────────────────────────────────────
    # snd_soc_avs is the Intel Audio Virtualization engine.  Debian loads
    # it alongside the SOF stack for full Tiger Lake audio support.  Adding
    # it ensures the complete audio subsystem is available.
    "snd_soc_avs"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-7943bb7d-58d5-4251-8ca5-fc880a1880f6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-7943bb7d-58d5-4251-8ca5-fc880a1880f6" = {
    device = "/dev/disk/by-uuid/7943bb7d-58d5-4251-8ca5-fc880a1880f6";
    allowDiscards = true; # SSD TRIM support through LUKS
  };

  # Swap LUKS device — must be declared here so initrd knows to unlock it.
  # Without this, boot hangs for ~90 s waiting for /dev/mapper/luks-005db41c...
  boot.initrd.luks.devices."luks-005db41c-8e88-4454-b57c-4978ff19b4fb" = {
    device = "/dev/disk/by-uuid/005db41c-8e88-4454-b57c-4978ff19b4fb";
    allowDiscards = true; # Enables SSD TRIM through LUKS (root already has it)
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4C0E-8079";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-005db41c-8e88-4454-b57c-4978ff19b4fb"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
